### ISSUE TITLE
[ex_Radio_Browser_info.lua] freezes on loading languages

### ISSUE THREAD

**Issue by Vingolf** [ceever/Radio-Browser.info.lua#8] opened 2024-10-17 17:49 UTC
I encountered two issues with the search window:

1. **Language:**  **loading...** lets the extension **freeze:** 
![2024-10-17_Vlc_Radio-browser_ex_loading](https://github.com/user-attachments/assets/b271d014-c572-4ed4-a3c1-3e7692f44efb)

2. **Country:**- scrolling in the drop down menu is impossible:
![2024-10-17_Vlc_Radio-browser_ex_contry](https://github.com/user-attachments/assets/5145bfb3-60d8-4ea7-8d20-519057d37e89)

**Testet on Windows**
- Windows 10 Pro build 19045
- VLC 3.0.21 Vetinari.

**Comment by ceever** [comment] 2024-10-24 18:59
Hi

Thanks for your input.

1) "loading ..." is a generic title that is removed when the loading of the dropdown items has finished. So it is not really frozen, county loading just broke.
2) It looks like it broke after Armenia ... Unfortunately, I cannot reproduce the error neither on Linux nor on Windows. Such errors are mostly related to connection problems.

Can you start VLC with verbose in Terminal on Windows like this (WINDOWS+R > "cmd"):
<pre>
cd C:\Program Files\VideoLAN\VLC
vlc -vv
</pre>

Then redo your steps in VLC until the plugin breaks and copy all the output from the terminal and please get back to me.

**EDIT**: Sorry, you need to first open the message window to see any debug messages with VLC. You can do that in VLC here: "Tools" >> "Messages", or just push CTRL+M when in VLC.

NOTE, I am moving this repository to GitLab: https://gitlab.com/radio_dude/radio-browser_vlc

Please reopen the issue there if still existent and also try the updated *ex_Radio_Browser_info.lua* version there, which I changed slightly also using https requests now (but not related to the bug described here).

Best

**Closed as completed by ceever** 2024-10-24 18:59 UTC

**Comment by Vingolf** [comment] 2024-10-29 13:21
Hi ceever,

> Please reopen the issue there if still existent and also try the updated _ex_Radio_Browser_info.lua_ version there, 
which I changed slightly also using https requests now

The issue has vanished with the updated _ex_Radio_Browser_info.lua_ file 😃

Whatever you did, you did it right 👍

Vingolf
